// Offline asset generator. Rasterizes the pinned Lucide SVGs into small alpha
// masks; the dashboard tints them with its text color and does no SVG parsing.
#define NANOSVG_IMPLEMENTATION
#define NANOSVGRAST_IMPLEMENTATION
#include "nanosvg.h"
#include "nanosvgrast.h"
#include <array>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

int main(int argc, char **argv) {
    try {
        if (argc != 3)
            throw std::runtime_error("Usage: generate-sidebar-icons LUCIDE_DIRECTORY OUTPUT.h");
        std::ofstream output(argv[2], std::ios::binary | std::ios::trunc);
        if (!output)
            throw std::runtime_error("Cannot open generated header");
        output << "// Generated by scripts/generate-sidebar-icons.cpp from pinned Lucide SVGs.\n"
                  "// Notices: vendor/lucide/LICENSE and vendor/nanosvg/LICENSE.txt.\n"
                  "#pragma once\n\nnamespace sidebar_icons {\n"
                  "enum class Icon { Move3d, List, Mic, Settings, Info, RotateCcw };\n"
                  "struct Image { int width, height; const unsigned char *alpha; };\n";
        const std::array<const char *, 6> filenames{"move-3d", "list", "mic", "settings", "info", "rotate-ccw"};
        const std::array<const char *, 6> names{"move3d", "list", "mic", "settings", "info", "rotateCcw"};
        std::unique_ptr<NSVGrasterizer, decltype(&nsvgDeleteRasterizer)>
            rasterizer(nsvgCreateRasterizer(), nsvgDeleteRasterizer);
        if (!rasterizer)
            throw std::runtime_error("Cannot create SVG rasterizer");
        for (size_t index = 0; index < filenames.size(); ++index) {
            const int size = index == 5 ? 18 : 26;
            std::ifstream source(std::filesystem::path(argv[1]) /
                                 (std::string(filenames[index]) + ".svg"), std::ios::binary);
            if (!source)
                throw std::runtime_error("Missing pinned Lucide SVG");
            std::string svg((std::istreambuf_iterator<char>(source)), {});
            // NanoSVG has no inherited currentColor; only alpha is retained.
            for (size_t pos = 0; (pos = svg.find("currentColor", pos)) != std::string::npos;)
                svg.replace(pos, 12, "#ffffff");
            std::unique_ptr<NSVGimage, decltype(&nsvgDelete)>
                image(nsvgParse(svg.data(), "px", 96), nsvgDelete);
            if (!image || image->width != 24 || image->height != 24 || !image->shapes)
                throw std::runtime_error("Expected a 24px Lucide SVG");
            std::vector<unsigned char> rgba(size * size * 4);
            nsvgRasterize(rasterizer.get(), image.get(), 0, 0, size / 24.f, rgba.data(),
                          size, size, size * 4);
            output << "inline constexpr unsigned char " << names[index] << "[] = {\n";
            for (int y = 0; y < size; ++y) {
                output << "    ";
                for (int x = 0; x < size; ++x)
                    output << static_cast<unsigned int>(rgba[(y * size + x) * 4 + 3]) << ',';
                output << '\n';
            }
            output << "};\n";
        }
        output << "inline Image get(Icon icon) {\n"
                  "    switch (icon) {\n"
                  "    case Icon::Move3d: return {26, 26, move3d};\n"
                  "    case Icon::List: return {26, 26, list};\n"
                  "    case Icon::Mic: return {26, 26, mic};\n"
                  "    case Icon::Settings: return {26, 26, settings};\n"
                  "    case Icon::Info: return {26, 26, info};\n"
                  "    case Icon::RotateCcw: return {18, 18, rotateCcw};\n"
                  "    }\n"
                  "    return {26, 26, info};\n"
                  "}\n} // namespace sidebar_icons\n";
        if (!output)
            throw std::runtime_error("Cannot finish generated header");
    } catch (const std::exception &e) {
        std::cerr << e.what() << '\n';
        return 1;
    }
}
