cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED PROJECT_ROOT)
  get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

if(MODE STREQUAL "dependencies")
  file(READ "${PROJECT_ROOT}/dependencies.lock.json" lock)
  string(JSON count LENGTH "${lock}" files)
  if(count LESS 1)
    message(FATAL_ERROR "Dependency lockfile contains no files")
  endif()
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    string(JSON path GET "${lock}" files ${index} path)
    string(JSON expected GET "${lock}" files ${index} sha256)
    string(LENGTH "${expected}" hash_length)
    if(NOT path MATCHES "^vendor/[a-zA-Z0-9_./-]+$" OR path MATCHES "\\.\\.")
      message(FATAL_ERROR "Invalid dependency path: ${path}")
    endif()
    if(NOT hash_length EQUAL 64 OR NOT expected MATCHES "^[a-fA-F0-9]+$")
      message(FATAL_ERROR "Invalid dependency checksum: ${path}")
    endif()
    if(NOT EXISTS "${PROJECT_ROOT}/${path}" OR IS_DIRECTORY "${PROJECT_ROOT}/${path}")
      message(FATAL_ERROR "Missing dependency: ${path}")
    endif()
    file(SHA256 "${PROJECT_ROOT}/${path}" actual)
    string(TOLOWER "${expected}" expected)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "Dependency changed: ${path}. Review it and update the lock deliberately.")
    endif()
  endforeach()
  message(STATUS "Verified ${count} pinned dependency files.")
elseif(MODE STREQUAL "toolchain")
  file(READ "${PROJECT_ROOT}/dependencies.lock.json" lock)
  string(JSON version GET "${lock}" toolchains zig version)
  string(JSON url GET "${lock}" toolchains zig url)
  string(JSON sha GET "${lock}" toolchains zig sha256)
  string(LENGTH "${sha}" hash_length)
  if(NOT version MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$" OR
     NOT url MATCHES "^https://[^\r\n]+$" OR
     NOT hash_length EQUAL 64 OR NOT sha MATCHES "^[a-fA-F0-9]+$")
    message(FATAL_ERROR "Invalid pinned Zig toolchain metadata")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${version}\n${url}\n${sha}"
    COMMAND_ERROR_IS_FATAL ANY)
elseif(MODE STREQUAL "manifest")
  if(NOT DEFINED PACKAGE_ROOT)
    message(FATAL_ERROR "PACKAGE_ROOT is required")
  endif()
  foreach(path IN ITEMS input/actions.json input/bindings_frame.json frame-advanced-settings.vrmanifest)
    file(READ "${PACKAGE_ROOT}/${path}" json)
    string(JSON type TYPE "${json}")
    if(NOT type STREQUAL "OBJECT")
      message(FATAL_ERROR "Expected a JSON object: ${path}")
    endif()
  endforeach()
  string(JSON count LENGTH "${json}" applications)
  set(matches 0)
  if(count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE ${last})
      string(JSON key GET "${json}" applications ${index} app_key)
      if(key STREQUAL "local.frame-space-drag")
        math(EXPR matches "${matches} + 1")
        string(JSON executable GET "${json}" applications ${index} binary_path_linux_arm)
        string(JSON actions GET "${json}" applications ${index} action_manifest_path)
        string(JSON overlay GET "${json}" applications ${index} is_dashboard_overlay)
        string(JSON icon GET "${json}" applications ${index} image_path)
        if(NOT executable STREQUAL "frame-advanced-settings" OR
           NOT actions STREQUAL "input/actions.json" OR NOT overlay OR
           NOT icon STREQUAL "assets/icons/frame-advanced-settings.png")
          message(FATAL_ERROR "Application manifest has an unexpected executable, actions, dashboard role, or icon")
        endif()
      endif()
    endforeach()
  endif()
  if(NOT matches EQUAL 1)
    message(FATAL_ERROR "Application manifest must declare exactly one local.frame-space-drag application")
  endif()
else()
  message(FATAL_ERROR "Unknown metadata mode: ${MODE}")
endif()
